title: EL BLOGG DE KYA
description:  Videojuegos y retos
permalink: ':title/'
baseurl: "/" 
url: "https://kyabloggs.github.io/" 
site-twitter: 


author: EL BLOGG DE KYA
author-img: oh.jpg
about-author: Un blogg en el que se harán retos con mi hermana o con invitados sorpresa y en el que también se jugarán a videojuegos.
social-twitter: 
social-facebook: 
social-github: 
social-linkedin: 
social-email: 




# Disqus
discus-identifier:  

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
